# Generated by Django 3.2.12 on 2022-04-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='twitter_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.CharField(max_length=300)),
                ('user', models.CharField(default=None, max_length=300, null=True)),
                ('created_at', models.CharField(default='', max_length=200)),
                ('hashtags', models.CharField(default='', max_length=200)),
                ('user_mentions', models.CharField(default='', max_length=500)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
